name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched the existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I am running the latest version of the application
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (Vue.js)
        - Backend (Go API)
        - Database (PostgreSQL)
        - Authentication
        - Recipe Management
        - AI/LLM Integration
        - E2E Tests
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Feature completely broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic problem
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12, Ubuntu 20.04]
        - Browser: [e.g. Chrome 91, Firefox 89, Safari 14]
        - Node.js version: [e.g. 18.16.0]
        - Go version: [e.g. 1.23.0]
        - Docker version: [e.g. 20.10.17]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error logs or console output
      placeholder: Paste error logs here...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or paste URLs

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: reproduction
    attributes:
      label: Reproducibility
      description: Can you consistently reproduce this bug?
      options:
        - label: Yes, I can reproduce this consistently
        - label: No, it happens randomly
        - label: Only under specific conditions

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How does this bug affect your usage?
      options:
        - Blocks me completely
        - Significantly impacts my workflow
        - Minor inconvenience
        - Doesn't affect my current usage