name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched the existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the roadmap and documentation
          required: true
        - label: This is a feature request, not a bug report
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application would this feature affect?
      options:
        - Frontend (Vue.js)
        - Backend (Go API)
        - Database (PostgreSQL)
        - Authentication
        - Recipe Management
        - AI/LLM Integration
        - User Interface/UX
        - Performance
        - Testing
        - Documentation
        - CI/CD Pipeline
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Needed for basic functionality
        - High - Would significantly improve the application
        - Medium - Would be a nice addition
        - Low - Nice to have but not essential
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        A clear and concise description of any alternative solutions 
        or features you've considered.

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        Provide specific examples of how this feature would be used:
        1. As a [user type], I want to [action] so that [benefit]
        2. When [scenario], I should be able to [action]
        3. etc.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be complete?
      placeholder: |
        List the specific requirements that define when this feature is done:
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: dropdown
    id: user-type
    attributes:
      label: Target User
      description: Who would primarily benefit from this feature?
      options:
        - End users (recipe creators/browsers)
        - Administrators
        - Developers
        - All users
        - Other
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups or wireframes
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects to consider?
      placeholder: |
        - Database schema changes needed?
        - API changes required?
        - Frontend component changes?
        - Performance implications?
        - Security considerations?
        - Third-party integrations?

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes
        - label: This feature is backwards compatible
        - label: I'm not sure about compatibility impact

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: |
        - Links to similar features in other applications
        - Research or user feedback supporting this request
        - Timeline considerations
        - Any other relevant information

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I would prefer someone else implements this